projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      load:
        csv: src/players.csv,
        mutation: post,
        mapping: {
          "name" : "name",
          "team" : "team",
          "position" : "position",
          "closingtime" : "closingtime",
          "fangraphsid" : "fangraphsid",
          "fantraxid" : "fantraxid"
        }
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
