projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      load:
        csv: src/players.csv,
        mutation: post,
        mapping: {
          "name" : "args.name",
          "team" : "args.team",
          "position" : "args.position",
          "closingtime" : "args.closingtime",
          "fangraphsid" : "args.fangraphsid",
          "fantraxid" : "args.fantraxid"
        }
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
